%YAML 1.2
---

# Name of the dockerized container, this will be main tag
# Docker image name'll be:
#   ${name}:${rosdistro}
name: dcat

# ROS Distribution for dockerized catkin
rosdistro:
  - kinetic
  - melodic

# Source directory of catkin workspace
catkin_src: ~/Sandbox/ros_ws/src

# Docker Parameters
docker_params:
  envs: "bash"
